### ISSUE TITLE
New GUI DFT search fields

### ISSUE THREAD

**Issue by ondracka** [ondracka/nomad#1]
In https://nomad-lab.eu/prod/v1/staging/gui/search/calculations filters/method/DFT  add a new section (visually identical with what we have now for "Relativity Method" or "Core Electron Treatment") for:

- [ ] Van der Waals correction: the corresponding field, https://nomad-lab.eu/prod/v1/staging/gui/analyze/metainfo/nomad.datamodel.datamodel.EntryArchive/results/method/simulation/dft/van_der_Waals_method

- [ ] Number of spin channels
https://nomad-lab.eu/prod/v1/staging/gui/analyze/metainfo/nomad.datamodel.datamodel.EntryArchive/run/method/electronic/n_spin_channels

Minor changes to the elasticsearch might be needed, corresponding code lives in nomad/datamodel/results.py

It probably would be easiest to find the code for "Relativity Method" or "Core Electron Treatment" searches, find the corresponding commits/merge requests with git blame and just mirror that.

For this to be 100% usable it might need a parser changes, for example for the vdW:
- to check status of vdW parsing at least in the most relevant parsers (Wien2k, QE, VASP, OpenMX, exciting) if this is actually parsed now
- to check that parsers that parse vdW settings now also correctly insert empty string so that we can distinguish between no vdW correction and "unavailable", meaning no parser support.
- But this is not directly related and concerns the parsers instead.

**Comment by ondracka** [comment]
I have no idea if this will need also some backend changes (like index the needed stuff in the elasticsearch), probably would be easier to find the code for "Relativity Method" or "Core Electron Treatment" searches, find the corresponding commits/merge requests with git blame and just mirror that.

**Comment by ondracka** [comment]
Actually this should be already in the elasticsearch so no backend changes should be needed.

https://nomad-lab.eu/prod/v1/staging/gui/analyze/metainfo/nomad.datamodel.datamodel.EntryArchive/results/method/simulation/dft/van_der_Waals_method

**Comment by ondracka** [comment]
I was looking in more details how it all works, the stuff that is saved in the elastic search is defined in nomad/datamodel/results.py while the population of the values happens during normalizing the relevant part for the stuff in here is in nomad/normalizing/method.py  For the number of spin channels, there is already a `is_spinpolarized` field in the elastic search, so we can just use that. similarly for the van der Waals correction, there is `van_der_Waals_method`. However there we should add a default "unavailable" if the key was not parsed at all and also instead of the empty string indicating there is no vdW correction I would prefer to save something like "none" into the database (or alternatively we can do this replacement in the GUI).

**Comment by ondracka** [comment]
Here is a test upload for the spin-polarization. It contains three entries, one which is detected as spin-polarized, one that is not spin-polarized and one where the parser doesn't support the detection yet. 
[spin-polarization-tests.zip](https://github.com/ondracka/nomad/files/13715828/spin-polarization-tests.zip)

**Comment by jfrodlova** [comment]
Thanks. 
I found a vDW entry in results.py and added corresponding filters to js files, but I am not sure how to test it. Could you provide some data for vDW, as well?

**Comment by jfrodlova** [comment]
> For the number of spin channels, there is already a `is_spinpolarized` field in the elastic search, so we can just use that. Similarly for the van der Waals correction, there is `van_der_Waals_method`. 

I did not find `is_spinpolarized`, only `spin_polarized`. Is that what you meant? 
Also, I am not sure how to make a filter _Number of spin channels_ (which sounds like an integer quantity) from a boolean `spin_polarized`.
Does it mean that _Number of spin channels_ can only be 0 or 1?

**Comment by ondracka** [comment]
Number of spin channels can be >=1.
Regarding the spin_polarization, this works the other way around. From the integer quantity `n_spin_channels` that we get from the parsers, and it seems to be properly extracted in nomad/normalizing/method.py. So here I think all we need is a knob in the GUI for the search

**Comment by ondracka** [comment]
Regarding the vdW, it seems the parser support is worse than I thought, so far I wasn't able to find single working example, I'll keep digging. But we will probably have to make some parser fixing later.

**Comment by ondracka** [comment]
I added quick support for vdW to the openmx parser, the branch is here: https://github.com/ondracka/electronic-parsers/tree/openmx_vdw
Updating nomad to use that branch is a bit tricky, the electronic-parsers are a submodule of nomad, you need to:

1. change the submodule to point to my fork
2. select the correct branch/commit
3. git submodule update

I hope @mfrodl can help with the git-fu, if you run into issues, just let me know (also make sure you have latest nomad develop, there were some interface breaking changes recently). I also committed a test case, you can upload it to the oasis for testing (and also other openmx testcases from there which don't have any vdW correction for reference).
