### ISSUE TITLE
Custom eV/Å force units in the GUI.

### ISSUE THREAD

**Issue by ondracka** [ondracka/nomad#2]
One can set custom force units in using the top right units button.
https://nomad-lab.eu/prod/v1/staging/gui/search/calculations

The most commonly used force units are however electronvolts/Angstrom eV/Å and are not present. Currently the best option is "Atomic unit of force" which is actually in Hatree/Bohr radius, the conversion to eV/Å should be straightforward.

Some magic constants: http://greif.geo.berkeley.edu/~driver/conversions.html

Maybe a new definition in nomad/units/default_en.txt is all that is needed.

Also figure out how to make it default, Newtons are nice but completely meaningless at the atomic scale...

**Comment by jfrodlova** [comment]
I made some changes in nomad/units/default_en.txt and "eV/Å" is now shown in the list of units.
Now, I would like to test if the conversion works. 
So far, I did not find any fields using force units. Where could I find this kind of data for testing?

**Comment by ondracka** [comment]
I uploaded some Geometry Optimization calculations, you can check there at workflow/Geometry Optimization/Final Force Maximum.

Please send a PR with the change.

**Comment by ondracka** [comment]
@jfrodlova if you need a quick git intro just let me know.
